### ISSUE TITLE
Using only mysql binlog reader

### ISSUE THREAD

**Issue by hartfordfive** [vaquita/mysql#2]
How would I initialize the client to use only the binary log reader?

**Comment by nirbhayc** [comment]
Checkout the wiki for an example : https://github.com/vaquita/mysql/wiki/Replication-Binary-Logs

**Comment by hartfordfive** [comment]
Yes but I'm looking through your code to try to figure out what can create an instance of the `Binlog` struct as you need it in order to run the `Connect()` function on the struct instance:
https://github.com/vaquita/mysql/blob/master/binlog.go#L120

**Comment by nirbhayc** [comment]
```
...
var b mysql.Binlog
b.Connect(dsn)
...
```

**Comment by hartfordfive** [comment]
Ah...right, I should have caught that.  Thanks again for your help.
